[package]
name = "taskerctl"
version = "0.1.7"
edition = "2021"
description = "a simple helper for managing tasker_service"
license = "GPL-3.0"
authors = ["Daniel M. email:danielmadmon@protonmail.com"]
repository = "https://github.com/DanielMadmon/taskerctl"
homepage = "https://github.com/DanielMadmon/taskerctl"


[dependencies]
clap = {version = "4.3.0", features = ["derive"]}
comfy-table = "6.1.4"
derive = "1.0.0"
features = "0.10.0"
hostname = "0.3.1"
simple-home-dir = "0.1.2"
sysinfo = "0.29.0"
tasker_lib = "0.0.3"
terminal-text-styler = "0.1.0"
