[package]
name = "tasker_service"
version = "0.1.3"
edition = "2021"
description = "a service for executing time based commands"
license = "GPL-3.0"
authors = ["Daniel M. email:danielmadmon@protonmail.com"]


[dependencies]
tasker_lib = "0.0.1"
