[package]
name = "tasker_gui"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"


[dependencies]
slint = "1.0.2"
tasker_lib = { version = "0.0.3", path = "../../lib/tasker_lib" }

[build-dependencies]
slint-build = "1.0.2"