[package]
name = "tasker_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9.0"
tasker_lib = { version = "0.0.3", path = "../../lib/tasker_lib" }

